#!/bin/bash
#MISE description="Initialize Database (Migrate & Seed)"
#MISE depends=["up"]
echo "🗄️ Waiting for database..."
sleep 5
echo "OR Running migrations..."
docker-compose exec backend alembic upgrade head
echo "🌱 Seeding data..."
docker-compose exec backend sh -c "PYTHONPATH=. python scripts/seed.py"
