#!/bin/bash
#MISE description="Install Git Hooks (pre-commit)"
if command -v pre-commit >/dev/null 2>&1; then
    pre-commit install
    pre-commit install --hook-type pre-push
    echo "✅ Git Hooks installed."
else
    echo "⚠️ pre-commit not found. Skipping."
fi
